### ISSUE TITLE
documentation uses `url` module which is no longer maintained

### ISSUE THREAD

**Issue by wuch-g2v** [python-jsonschema/referencing#104]
On building documentation `url` module is required
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/builder/rpmbuild/BUILD/referencing-0.31.1/docs/conf.py", line 3, in <module>
    from url import URL
ModuleNotFoundError: No module named 'url'
```
This module had last release in 2017 https://pypi.org/project/url/#history and is not maintained since 2020 https://github.com/seomoz/url-py

**Comment by Julian** [comment]
That isn't the correct module. See the build script. (and requirements files) which are the only supported way to develop the project.

**Comment by Julian** [comment]
(to be more explicit, the project depended on is called `url-py`)
