### ISSUE TITLE
Build fails with ValueError: Unknown classifier in field `project.classifiers`: Topic :: File Formats :: JSON

### ISSUE THREAD

**Issue by foolnotion** [python-jsonschema/referencing#55]
Hi, it seems that the project metadata is wrong.

Full build log here:

```
Processing /build/referencing-0.29.1
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/vwk3jva2a07pwvsa7qxvzh9znzk47z28-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_proc>
      main()
    File "/nix/store/vwk3jva2a07pwvsa7qxvzh9znzk47z28-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_proc>
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/vwk3jva2a07pwvsa7qxvzh9znzk47z28-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_proc>
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/nix/store/6kvyd5r4zp7prfwh1zm0k6d049di1wmw-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/build.py", line 56, in build_whe>
      return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
    File "/nix/store/6kvyd5r4zp7prfwh1zm0k6d049di1wmw-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", l>
      self.metadata.validate_fields()
    File "/nix/store/6kvyd5r4zp7prfwh1zm0k6d049di1wmw-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 244, in >
      self.core.validate_fields()
    File "/nix/store/6kvyd5r4zp7prfwh1zm0k6d049di1wmw-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1326, in>
      getattr(self, attribute)
    File "/nix/store/6kvyd5r4zp7prfwh1zm0k6d049di1wmw-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 979, in >
      raise ValueError(message)
  ValueError: Unknown classifier in field `project.classifiers`: Topic :: File Formats :: JSON
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /nix/store/1r6n7v2wam7gkr18gxccpg7p5ywgw551-python3-3.10.12/bin/python3.10 /nix/store/vwk3jva2a07pwvsa7qxvzh9znzk47z28-python3.10-pip-23.>
  cwd: /build/referencing-0.29.1
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Julian** [comment]
Something there in your setup is using old versions of build tools -- specifically, that classifier requires a recent version of [trove-classifiers](https://pypi.org/project/trove-classifiers/).

I'd assume your nix setup is pinning dependencies as part of the build, and doing so for versions which are too old -- in CI here the build process works fine, so if the above hint doesn't help I'd need a command that reproduces to decide whether there's anything to fix here.

**Comment by foolnotion** [comment]
> Something there in your setup is using old versions of build tools -- specifically, that classifier requires a recent version of [trove-classifiers](https://pypi.org/project/trove-classifiers/).

Thanks, just how recent are we talking about? I'm using `2023.5.24` although I see a new version was released two hours ago.

**Comment by Julian** [comment]
`2023.5.24` of what? I'm talking about your `pip`, `hatchling`, etc, which are out of date (neither version appearing there are the one one would get from doing a build today on `jsonschema`) -- essentially the supported build process is the "usual" Python one, as building jsonschema is generally something part of its development process not end-user facing (I definitely don't mind making nix builds work but yeah like I said something I suspect is more wrong with that than anything related to the package)

**Comment by Julian** [comment]
Oh, you mean 2023.5.24 of course -- yeah I don't know, looks like 2023.4.25 or newer is what you need, but I probably can't help diagnose without a way to reproduce and would probably ask you figure it out by comparing to a "normal" build and seeing what you need to tweak.

**Comment by foolnotion** [comment]
After further investigation this problem seems to occur with other packages as well, and originates with hatchling. I couldn't exactly figure out what was going on but I don't think it's an issue with `python-jsonschema`.
