### ISSUE TITLE
Import fails on typing.py: AttributeError: type object 'Mapping' has no attribute '__class_getitem__'

### ISSUE THREAD

**Issue by koenigdavidmj** [python-jsonschema/referencing#58]
My project's unit tests are failing to pull in `flask_restx`, now that typing-extensions 4.7.0 has been released and pulls in referencing. The backtrace is this:

```
.tox/pypy3-test/lib/pypy3.8/site-packages/flask_restx/__init__.py:1: in <module>
    from . import fields, reqparse, apidoc, inputs, cors
.tox/pypy3-test/lib/pypy3.8/site-packages/flask_restx/reqparse.py:15: in <module>
    from .model import Model
.tox/pypy3-test/lib/pypy3.8/site-packages/flask_restx/model.py:13: in <module>
    from jsonschema import Draft4Validator
.tox/pypy3-test/lib/pypy3.8/site-packages/jsonschema/__init__.py:13: in <module>
    from jsonschema._format import FormatChecker
.tox/pypy3-test/lib/pypy3.8/site-packages/jsonschema/_format.py:11: in <module>
    from jsonschema.exceptions import FormatError
.tox/pypy3-test/lib/pypy3.8/site-packages/jsonschema/exceptions.py:15: in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
.tox/pypy3-test/lib/pypy3.8/site-packages/referencing/__init__.py:4: in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
.tox/pypy3-test/lib/pypy3.8/site-packages/referencing/_core.py:10: in <module>
    from referencing import exceptions
.tox/pypy3-test/lib/pypy3.8/site-packages/referencing/exceptions.py:11: in <module>
    from referencing.typing import URI
.tox/pypy3-test/lib/pypy3.8/site-packages/referencing/typing.py:11: in <module>
    Mapping[str, str]
E   AttributeError: type object 'Mapping' has no attribute '__class_getitem__'
```

This is within the context of pytest, under PyPy 3.8. I'm having trouble reproducing this minimally, because any attempts to reproduce are giving me a `TypeError`, like your code expects.

If I run this directly in a console, it returns the expected TypeError.

```
from collections.abc import Mapping as Mapping
Mapping[str, str]
```

If I do this, I get the same AttributeError:

```
Mapping.__class_getitem__
```

**Comment by Julian** [comment]
If you drop into a debugger just before that line, what do you see?

Hard to do anything without a reproducer -- the library's tested under PyPy3 so I'm not aware of any issues.

A random guess is something is monkey patching `collections.abc.Mapping`, but impossible to know for sure if I can't poke.

**Comment by koenigdavidmj** [comment]
I'm not able to reproduce on my local machine (tested on CPython because I'm having weird unrelated PyPy issues). I did add some code to my CICD build to printf-debug it:

```
from collections.abc import Mapping as Mapping
print("KOENIG rt.Mapping is", Mapping)
print("KOENIG rt.Mapping is module", Mapping.__module__)
Mapping[str,str]
print("KOENIG END")
```

```
KOENIG rt.Mapping is <class 'collections.abc.Mapping'>
KOENIG rt.Mapping is module collections.abc
ImportError while loading conftest '(path redacted)'
(redacted): in <module>
    Mapping[str,str]
E   AttributeError: type object 'Mapping' has no attribute '__class_getitem__'
```

In 3.8, it's expected that Mapping will not have a `__class_getitem__`, so I'm not sure why any monkey-patching would result in this. I can't prove this, but it feels like something is rewriting `Mapping[str, str]` into a direct call to `Mapping.__class_getitem__`. If I do that, I get the same error that I initially reported:

```
>>> from collections.abc import Mapping

>>> Mapping[str, str]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'ABCMeta' object is not subscriptable

>>> Mapping.__class_getitem__(Mapping, (str, str))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Mapping' has no attribute '__class_getitem__'
```

**Comment by koenigdavidmj** [comment]
It's safe to close this; it's not your library. We rolled back, and now we're seeing the same thing pop up in another library.
